- hosts: kuberenetes
# - hosts: all
  become: true
  roles:
    - role: docker_file
  # tasks:
  #   - name: docker.ioのインストール
  #     apt:
  #       name: docker.io
  #       state: latest
  #       update_cache: true
  #       cache_valid_time: 3600
  #   - name: docker userへの追加
  #     command: usermod -aG docker karosu