- hosts: kuberenetes
# - hosts: all
  become: true
  vars:
  # userdata: karosu
    os: xUbuntu_20.04
    version: "1.20"
  roles:
    - role: cri-o_file
- hosts: kuberenetes
  become: true
  roles:
    - role: k8s-cri-o
  # tasks:
  #   - name: docker.ioのインストール
  #     apt:
  #       name: docker.io
  #       state: latest
  #       update_cache: true
  #       cache_valid_time: 3600
  #   - name: docker userへの追加
  #     command: usermod -aG docker karosu